#!/bin/bash

# Get the directory this script is currently located in
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Project root is one level above this scripts directory
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Run tree command in project root
tree "$PROJECT_ROOT" -P '*.hpp|*.cpp|*.h|*.c' -I 'build' --prune -n
